# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/ECE 440/h3/h3/h3.cache/wt} [current_project]
set_property parent.project_path {D:/ECE 440/h3/h3/h3.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {d:/ECE 440/h3/h3/h3.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {{D:/ECE 440/h3/h3/h3.srcs/sources_1/new/ffwb.sv}}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top ffwb -part xc7z010clg400-1


write_checkpoint -force -noxdef ffwb.dcp

catch { report_utilization -file ffwb_utilization_synth.rpt -pb ffwb_utilization_synth.pb }
