# 
# Synthesis run script generated by Vivado
# 

set_param general.maxThreads 8
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -msgmgr_mode ooc_run
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/ECE_440/project7/project7/project7.cache/wt [current_project]
set_property parent.project_path F:/ECE_440/project7/project7/project7.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_output_repo f:/ECE_440/project7/project7/project7.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_ip -quiet f:/ECE_440/project7/project7/project7.srcs/sources_1/bd/first_zynq_system/ip/first_zynq_system_rst_ps7_0_100M_0/first_zynq_system_rst_ps7_0_100M_0.xci
set_property is_locked true [get_files f:/ECE_440/project7/project7/project7.srcs/sources_1/bd/first_zynq_system/ip/first_zynq_system_rst_ps7_0_100M_0/first_zynq_system_rst_ps7_0_100M_0.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

set cached_ip [config_ip_cache -export -no_bom -use_project_ipc -dir F:/ECE_440/project7/project7/project7.runs/first_zynq_system_rst_ps7_0_100M_0_synth_1 -new_name first_zynq_system_rst_ps7_0_100M_0 -ip [get_ips first_zynq_system_rst_ps7_0_100M_0]]

if { $cached_ip eq {} } {

synth_design -top first_zynq_system_rst_ps7_0_100M_0 -part xc7z010clg400-1 -mode out_of_context

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
catch {
 write_checkpoint -force -noxdef -rename_prefix first_zynq_system_rst_ps7_0_100M_0_ first_zynq_system_rst_ps7_0_100M_0.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ first_zynq_system_rst_ps7_0_100M_0_stub.v
 lappend ipCachedFiles first_zynq_system_rst_ps7_0_100M_0_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ first_zynq_system_rst_ps7_0_100M_0_stub.vhdl
 lappend ipCachedFiles first_zynq_system_rst_ps7_0_100M_0_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ first_zynq_system_rst_ps7_0_100M_0_sim_netlist.v
 lappend ipCachedFiles first_zynq_system_rst_ps7_0_100M_0_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ first_zynq_system_rst_ps7_0_100M_0_sim_netlist.vhdl
 lappend ipCachedFiles first_zynq_system_rst_ps7_0_100M_0_sim_netlist.vhdl

 config_ip_cache -add -dcp first_zynq_system_rst_ps7_0_100M_0.dcp -move_files $ipCachedFiles -use_project_ipc -ip [get_ips first_zynq_system_rst_ps7_0_100M_0]
}

rename_ref -prefix_all first_zynq_system_rst_ps7_0_100M_0_

write_checkpoint -force -noxdef first_zynq_system_rst_ps7_0_100M_0.dcp

catch { report_utilization -file first_zynq_system_rst_ps7_0_100M_0_utilization_synth.rpt -pb first_zynq_system_rst_ps7_0_100M_0_utilization_synth.pb }

if { [catch {
  file copy -force F:/ECE_440/project7/project7/project7.runs/first_zynq_system_rst_ps7_0_100M_0_synth_1/first_zynq_system_rst_ps7_0_100M_0.dcp f:/ECE_440/project7/project7/project7.srcs/sources_1/bd/first_zynq_system/ip/first_zynq_system_rst_ps7_0_100M_0/first_zynq_system_rst_ps7_0_100M_0.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub f:/ECE_440/project7/project7/project7.srcs/sources_1/bd/first_zynq_system/ip/first_zynq_system_rst_ps7_0_100M_0/first_zynq_system_rst_ps7_0_100M_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub f:/ECE_440/project7/project7/project7.srcs/sources_1/bd/first_zynq_system/ip/first_zynq_system_rst_ps7_0_100M_0/first_zynq_system_rst_ps7_0_100M_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim f:/ECE_440/project7/project7/project7.srcs/sources_1/bd/first_zynq_system/ip/first_zynq_system_rst_ps7_0_100M_0/first_zynq_system_rst_ps7_0_100M_0_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim f:/ECE_440/project7/project7/project7.srcs/sources_1/bd/first_zynq_system/ip/first_zynq_system_rst_ps7_0_100M_0/first_zynq_system_rst_ps7_0_100M_0_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


if { [catch {
  file copy -force F:/ECE_440/project7/project7/project7.runs/first_zynq_system_rst_ps7_0_100M_0_synth_1/first_zynq_system_rst_ps7_0_100M_0.dcp f:/ECE_440/project7/project7/project7.srcs/sources_1/bd/first_zynq_system/ip/first_zynq_system_rst_ps7_0_100M_0/first_zynq_system_rst_ps7_0_100M_0.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  file rename -force F:/ECE_440/project7/project7/project7.runs/first_zynq_system_rst_ps7_0_100M_0_synth_1/first_zynq_system_rst_ps7_0_100M_0_stub.v f:/ECE_440/project7/project7/project7.srcs/sources_1/bd/first_zynq_system/ip/first_zynq_system_rst_ps7_0_100M_0/first_zynq_system_rst_ps7_0_100M_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force F:/ECE_440/project7/project7/project7.runs/first_zynq_system_rst_ps7_0_100M_0_synth_1/first_zynq_system_rst_ps7_0_100M_0_stub.vhdl f:/ECE_440/project7/project7/project7.srcs/sources_1/bd/first_zynq_system/ip/first_zynq_system_rst_ps7_0_100M_0/first_zynq_system_rst_ps7_0_100M_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force F:/ECE_440/project7/project7/project7.runs/first_zynq_system_rst_ps7_0_100M_0_synth_1/first_zynq_system_rst_ps7_0_100M_0_sim_netlist.v f:/ECE_440/project7/project7/project7.srcs/sources_1/bd/first_zynq_system/ip/first_zynq_system_rst_ps7_0_100M_0/first_zynq_system_rst_ps7_0_100M_0_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  file rename -force F:/ECE_440/project7/project7/project7.runs/first_zynq_system_rst_ps7_0_100M_0_synth_1/first_zynq_system_rst_ps7_0_100M_0_sim_netlist.vhdl f:/ECE_440/project7/project7/project7.srcs/sources_1/bd/first_zynq_system/ip/first_zynq_system_rst_ps7_0_100M_0/first_zynq_system_rst_ps7_0_100M_0_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

}; # end if cached_ip 

if {[file isdir F:/ECE_440/project7/project7/project7.ip_user_files/ip/first_zynq_system_rst_ps7_0_100M_0]} {
  catch { 
    file copy -force f:/ECE_440/project7/project7/project7.srcs/sources_1/bd/first_zynq_system/ip/first_zynq_system_rst_ps7_0_100M_0/first_zynq_system_rst_ps7_0_100M_0_stub.v F:/ECE_440/project7/project7/project7.ip_user_files/ip/first_zynq_system_rst_ps7_0_100M_0
  }
}

if {[file isdir F:/ECE_440/project7/project7/project7.ip_user_files/ip/first_zynq_system_rst_ps7_0_100M_0]} {
  catch { 
    file copy -force f:/ECE_440/project7/project7/project7.srcs/sources_1/bd/first_zynq_system/ip/first_zynq_system_rst_ps7_0_100M_0/first_zynq_system_rst_ps7_0_100M_0_stub.vhdl F:/ECE_440/project7/project7/project7.ip_user_files/ip/first_zynq_system_rst_ps7_0_100M_0
  }
}
