# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/ECE 440/project5/project5/project5.cache/wt} [current_project]
set_property parent.project_path {D:/ECE 440/project5/project5/project5.xpr} [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {d:/ECE 440/project5/project5/project5.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files {{D:/ECE 440/project5/project5/project5.srcs/sources_1/new/init.coe}}
add_files -quiet {{d:/ECE 440/project5/project5/project5.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.dcp}}
set_property used_in_implementation false [get_files {{d:/ECE 440/project5/project5/project5.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.dcp}}]
read_verilog -library xil_defaultlib -sv {
  {D:/ECE 440/project5/project5/project5.srcs/sources_1/imports/new/fsm.sv}
  {D:/ECE 440/project5/project5/project5.srcs/sources_1/imports/new/dp.sv}
  {D:/ECE 440/project5/project5/project5.srcs/sources_1/imports/new/gcd_core.sv}
  {D:/ECE 440/project5/project5/project5.srcs/sources_1/new/spi_ctrl.sv}
  {D:/ECE 440/project5/project5/project5.srcs/sources_1/new/core_wrapper.sv}
  {D:/ECE 440/project5/project5/project5.srcs/sources_1/new/mem_ctrl.sv}
  {D:/ECE 440/project5/project5/project5.srcs/sources_1/new/Project5.sv}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/ECE 440/project3/project3/project3.srcs/constrs_1/new/constraints.xdc}}
set_property used_in_implementation false [get_files {{D:/ECE 440/project3/project3/project3.srcs/constrs_1/new/constraints.xdc}}]


synth_design -top Project5 -part xc7z010clg400-1


write_checkpoint -force -noxdef Project5.dcp

catch { report_utilization -file Project5_utilization_synth.rpt -pb Project5_utilization_synth.pb }
