# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Cory Holt/Desktop/ECE_440/project8/project8/project8.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Cory Holt/Desktop/ECE_440/project8/project8/project8.xpr} [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/Cory Holt/Desktop/ECE_440/project8/project8/project8.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files {{C:/Users/Cory Holt/Desktop/ECE_440/project8/project8/codon.coe}}
add_files {{C:/Users/Cory Holt/Desktop/ECE_440/project8/project8/gene.coe}}
add_files -quiet {{c:/Users/Cory Holt/Desktop/ECE_440/project8/project8/project8.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.dcp}}
set_property used_in_implementation false [get_files {{c:/Users/Cory Holt/Desktop/ECE_440/project8/project8/project8.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.dcp}}]
add_files -quiet {{c:/Users/Cory Holt/Desktop/ECE_440/project8/project8/project8.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.dcp}}
set_property used_in_implementation false [get_files {{c:/Users/Cory Holt/Desktop/ECE_440/project8/project8/project8.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.dcp}}]
read_verilog -library xil_defaultlib -sv {
  {C:/Users/Cory Holt/Desktop/ECE_440/project8/project8/project8.srcs/sources_1/new/sequence_detector.sv}
  {C:/Users/Cory Holt/Desktop/ECE_440/project8/project8/project8.srcs/sources_1/new/codon_reader.sv}
  {C:/Users/Cory Holt/Desktop/ECE_440/project8/project8/project8.srcs/sources_1/new/DNA_sequencer.sv}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Cory Holt/Desktop/ECE_440/project8/project8/project8.srcs/constrs_1/imports/project8/constraints.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Cory Holt/Desktop/ECE_440/project8/project8/project8.srcs/constrs_1/imports/project8/constraints.xdc}}]


synth_design -top DNA_sequencer -part xc7z010clg400-1


write_checkpoint -force -noxdef DNA_sequencer.dcp

catch { report_utilization -file DNA_sequencer_utilization_synth.rpt -pb DNA_sequencer_utilization_synth.pb }
