# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/ECE_440/project7/project7/project7.srcs/sources_1/bd/first_zynq_system/ip/first_zynq_system_auto_pc_0/first_zynq_system_auto_pc_0.xci
# IP: The module: 'first_zynq_system_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/ECE_440/project7/project7/project7.srcs/sources_1/bd/first_zynq_system/ip/first_zynq_system_auto_pc_0/first_zynq_system_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'first_zynq_system_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: f:/ECE_440/project7/project7/project7.srcs/sources_1/bd/first_zynq_system/ip/first_zynq_system_auto_pc_0/first_zynq_system_auto_pc_0.xci
# IP: The module: 'first_zynq_system_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/ECE_440/project7/project7/project7.srcs/sources_1/bd/first_zynq_system/ip/first_zynq_system_auto_pc_0/first_zynq_system_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'first_zynq_system_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
