# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/ECE_440/project10/factorial_coprocessor/factorial_coprocessor.cache/wt [current_project]
set_property parent.project_path C:/ECE_440/project10/factorial_coprocessor/factorial_coprocessor.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/ECE_440/project10/factorial_coprocessor/factorial_coprocessor.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  C:/ECE_440/project10/factorial_coprocessor/factorial_coprocessor.srcs/sources_1/new/multiply.sv
  C:/ECE_440/project10/factorial_coprocessor/factorial_coprocessor.srcs/sources_1/new/factorial.sv
  C:/ECE_440/project10/factorial_coprocessor/factorial_coprocessor.srcs/sources_1/new/handshake_wrapper.sv
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top handshake_wrapper -part xc7z010clg400-1


write_checkpoint -force -noxdef handshake_wrapper.dcp

catch { report_utilization -file handshake_wrapper_utilization_synth.rpt -pb handshake_wrapper_utilization_synth.pb }
